# Generated by Django 2.0.8 on 2018-09-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomecandidato', models.CharField(max_length=50)),
                ('tipodecandidatura', models.CharField(max_length=50)),
                ('partido', models.CharField(max_length=50)),
                ('cidadecandidato', models.CharField(max_length=50)),
                ('coligacao', models.CharField(max_length=50)),
            ],
        ),
    ]
